### ISSUE TITLE
default_action initialization is incomplete

### ISSUE THREAD

**Issue by mbudiu-vmw** [williamtu/p4c-xdp#25]
This is in the #CONTROL_PLANE section of the generated header.

**Comment by mbudiu-vmw** [comment]
Where does the path /sys/fs/bpf/xdp/globals/tablename come from?

**Comment by williamtu** [comment]
TC creates this path.
There is a bpf filesystem created when loading the program using tc with command "ip link set dev eth0 xdp ..."
it will create the file at /sys/fs/bpf/xdp/globals/<map name> at loading time
it is "globals" because we set pinning=2 (GLOBAL_NS)
later on our control plane program can access the map by opening this path and get the file descriptor.

**Comment by mbudiu-vmw** [comment]
I thought we are not using TC anymore.

**Comment by williamtu** [comment]
you're right. 
I should say we use iproute2 tool as the BPF loader and load into XDP driver. The iproute2 will create the bpf filesystem.
